disabled_rules: # rule identifiers to exclude from running
#  - colon
#  - comma
#  - control_statement
#  - file_length
  - force_cast
#  - force_try
#  - function_body_length
#  - leading_whitespace
#  - line_length
  - nesting
  - large_tuple
  - unused_closure_parameter
#  - opening_brace
#  - operator_whitespace
#  - return_arrow_whitespace
#  - statement_position
#  - todo
#  - trailing_newline
#  - trailing_semicolon
#  - trailing_whitespace
#  - type_body_length
  - type_name
  - xctfail_message
#  - variable_name_max_length
#  - variable_name_min_length
#  - variable_name
#included: # paths to include during linting. `--path` is ignored if present. takes precendence over `excluded`.

function_parameter_count: 9

excluded: # paths to ignore during linting. overridden by `included`.
  - Carthage
  - Pods
  - Modules

line_length: 
    warning: 130
    error: 150
    ignores_comments: true

identifier_name:
  min_length: 2